	\context ChordNames 
		\chords {
		\set chordChanges = ##t
		% intro
		d4.:m d4.:sus4 d4.:m d4.:sus2
		d4.:m d4.:sus4 d4.:m d4.:sus2
		% "cordero de dios que quitas..."
		d2.:m g2.:m bes4. c4. d2.:m
		g2.:m d2.:m a2.:7
		d4.:m d4.:sus4 d4.:m d4.:sus2
		% "cordero de dios que quitas..."
		d2.:m g2.:m bes4. c4. d2.:m
		g2.:m d2.:m a2.:7
		d4.:m d4.:sus4 d4.:m d4.:sus2
		% "cordero de dios que quitas..."
		d2.:m g2.:m bes4. c4. d2.:m
		% "danos la paz..."
		r2.
		g2.:m a2.:7 d4.:m d4.:7
		g4.:m a4.:7 d2.:m
		g4.:m a4.:7 d4.:m d4.:7
		g4.:m a4.:7 d2.:m
		g4.:m a4.:7 d2.
		d2.
		}
